<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    '' => '',
    'O`zbekcha' => '',
    'АКЦИЯ ПОДАРОК' => '',
    'Аккаунт' => '',
    'Акции' => '',
    'Быстрота доставки' => '',
    'Ваш отзыв' => '',
    'Все каталоги' => '',
    'Доставка' => '',
    'Имя' => '',
    'Инстаграм' => '',
    'Как сделать покупку?' => '',
    'Каталог' => '',
    'Категории' => '',
    'Качество общения с клиентом' => '',
    'Контакты' => '',
    'Корзина' => '',
    'Меню' => '',
    'Номер телефона' => '',
    'О нас ?' => '',
    'О нас и Контакты' => '',
    'ОНЛАЙН ПОМОЩЬ' => '',
    'Опишите общее впечатление о сервисе SHOPPING. Так же, Вы можете оставить свои пожелания и предложения по улучшению услуг сервиса' => '',
    'Оставить отзыв' => '',
    'Параметр' => '',
    'Пожалуйста, оцените работу команды SHOPPING по следующим критериям' => '',
    'Поиск' => '',
    'Покупателям' => '',
    'Продукт' => '',
    'Рабочее время' => '',
    'Рассрочка' => '',
    'Русский' => '',
    'Социальная сеть' => '',
    'Способы оплаты' => '',
    'Телеграм' => '',
    'Телефон поддержки' => '',
    'Удобство заказа через веб-сайт' => '',
    'Условия рассрочки' => '',
    'Услуг' => '',
    'Фейсбук' => '',
    'Язык' => '',
    'онлайн оплата' => '',
    'служба доставки' => '',
    'создал cros' => '',
    'сум' => '',
];
